### ISSUE TITLE
Are Svg image overlays supported?

### ISSUE THREAD

**Issue by zeykafx** [salkuadrat/universe#1]
As the title suggest, are Svg image overlays supported by universe?
I'm asking this since flutter_map doesn't support svg overlays even using flutter_svg_provider.

Thanks a lot!

**Comment by zeykafx** [comment]
I tested with the package flutter_svg_provider, I don't get any exceptions but I cannot see the svg image on the map. I am using an svg chart for aviation and I have the correct bounds but I cannot see anything.

**Comment by salkuadrat** [comment]
Hi zeykafx,

For SvgOverlay, you can use [Custom Widget Overlay](https://github.com/salkuadrat/universe/blob/master/example/lib/src/overlay/widget.dart).

And to stop the map from refreshing you can set key to the map like in this example:  https://github.com/salkuadrat/universe/blob/master/example/lib/src/controller/move.dart

**Comment by zeykafx** [comment]
Great it works for PDFs,
Thanks for the quick reply and awesome library!

**Comment by salkuadrat** [comment]
Anytime, man. Happy to know it works.
