### ISSUE TITLE
Bugs: WMSTilelayer not working

### ISSUE THREAD

**Issue by veldrict** [salkuadrat/universe#2]
Hi,  I got a map from jimatt with wms. 

```
return U.Map(
        controller: MapController(),
        center: [-6.175520973390827, 106.82716012001038],
        zoom: 14,
        base: U.WMSTileLayer(
          "https://jimatt.com/wms?",
          format: "image/png",
          layers: "basemap",
          maxZoom: 21,
          transparent: false,
          crs: CRS.EPSG3857,
          additionalOptions: {'tiled': true, "PANE": 'labels'},
        ));
```

then i got an error like this 
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building JimattPage(dirty, state: _JimattPageState#7eaf5):
type "_InternalLinkedHashMap<String, Object> "is not a subtype of type "Map<String, String>?"

The relevant error-causing widget was
JimattPage
lib/main.dart:31
When the exception was thrown, this was the stack
#0      U.WMSTileLayer (package:universe/src/u.dart:4223:28)
#1      _JimattPageState.build
package:example_ddd/…/jimatt/jimatt_page.dart:43
#2      StatefulElement.build
package:flutter/…/widgets/framework.dart:4691
#3      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4574
#4      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4746
...
════════════════════════════════════════════════════════════════════════════════

```

**Comment by cmidgley** [comment]
I know almost nothing about this ... so take this with a grain of salt.  And I've just in the last hour starting looking at Universe and map providers.  So I thought I'd take a look at your problem mostly as a learning experience.  

When I go to the jimatt.com site and inspect the URL they request for a map image, I see something like this:

https://jimatt.com/wms?service=WMS&request=GetMap&layers=basemap&styles=&format=image%2Fjpeg&transparent=false&version=1.1.1&width=256&height=256&srs=EPSG%3A3857&bbox=11896047.58607855,-687321.7583403048,11897270.578531114,-686098.7658877411

However, I don't see similar parameters, such as lat/lon, being provided in your U.Map call.  As stated in the README:

```dart
U.Map(
  center: [51.555158, -0.108343],
  base: U.TileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
    attribution: 'Map data: &copy; OpenStreetMap contributors, SRTM | Map style: &copy; OpenTopoMap',
    maxZoom: 17,
  ),
)
```

You are missing the {z}, {x} and {y} parameters, as well as likely other parameters required by jimatt.com.  I'm guessing that the malformed URL is resulting in a non-image, such as when I hand type in a URL that is lacking the lat/lon (etc) I get a ERR_INVALID_RESPONSE.  

There are likely better ways to debug this ... but at a minimum, try building this using Chrome and inspect the network request and work on getting your request to submit a valid URL?

Hope this helps.  Good luck!

**Comment by veldrict** [comment]
> I know almost nothing about this ... so take this with a grain of salt. And I've just in the last hour starting looking at Universe and map providers. So I thought I'd take a look at your problem mostly as a learning experience.
> 
> When I go to the jimatt.com site and inspect the URL they request for a map image, I see something like this:
> 
> https://jimatt.com/wms?service=WMS&request=GetMap&layers=basemap&styles=&format=image%2Fjpeg&transparent=false&version=1.1.1&width=256&height=256&srs=EPSG%3A3857&bbox=11896047.58607855,-687321.7583403048,11897270.578531114,-686098.7658877411
> 
> However, I don't see similar parameters, such as lat/lon, being provided in your U.Map call. As stated in the README:
> 
> ```dart
> U.Map(
>   center: [51.555158, -0.108343],
>   base: U.TileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
>     attribution: 'Map data: &copy; OpenStreetMap contributors, SRTM | Map style: &copy; OpenTopoMap',
>     maxZoom: 17,
>   ),
> )
> ```
> 
> You are missing the {z}, {x} and {y} parameters, as well as likely other parameters required by jimatt.com. I'm guessing that the malformed URL is resulting in a non-image, such as when I hand type in a URL that is lacking the lat/lon (etc) I get a ERR_INVALID_RESPONSE.
> 
> There are likely better ways to debug this ... but at a minimum, try building this using Chrome and inspect the network request and work on getting your request to submit a valid URL?
> 
> Hope this helps. Good luck!

I already clone the code and check the error, then i try to change to fix it. It error because the U.WMSTileLayer use const <String,dynamic>{}. But in the L.WMSTileLayerOptions additionalOptions use <String,String> that make this error

>type "_InternalLinkedHashMap<String, Object> "is not a subtype of type "Map<String, String>?"

and the next error is on the _baseUrl on param service it use & at the begining that make the jimaat map not show and i check the url it like this
>https://jimatt.com/wms&service=WMS&request=GetMap&layers=basemap&styles=&format=image%2Fjpeg&transparent=false&version=1.1.1&width=256&height=256&srs=EPSG%3A3857&bbox=11896047.58607855,-687321.7583403048,11897270.578531114,-686098.7658877411

then i fix it from service i change into ?service=WMS and then it fix everything. and i can use the jimatt map.

Btw thanks for the help

**Comment by salkuadrat** [comment]
@veldrict please use the latest version I just update (universe v 1.1.0-nullsafety)

I've also included Jimatt as the example of WmsMap. You can see it at demo apk dan check the code [here].(https://github.com/salkuadrat/universe/blob/master/example/lib/src/map_provider/wms.dart).

![jimatt](https://user-images.githubusercontent.com/4903947/129709830-f8d2e420-295c-47fb-894e-c234624078de.png)
